version: 2
updates:
  # ---------- GitHub Actions ----------
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "advanced-security/advanced-security-dependency-graph"
      - "advanced-security/oss-maintainers"
    target-branch: "main"
    commit-message:
      prefix: deps
      prefix-development: chore
    labels:
      - "Dependencies"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  # ---------- JS / TS / NPM ----------
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "advanced-security/advanced-security-dependency-graph"
      - "advanced-security/oss-maintainers"
    target-branch: "main"
    commit-message:
      prefix: deps
      prefix-development: chore
    labels:
      - "Dependencies"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
