name: 'SPDX Dependency Submission Action'
description: 'Upload SPDX SBOM files to the dependency graph''s dependency submission API'
inputs:
  token:
    description: "GitHub Personal Access Token (PAT). Defaults to PAT provided by Actions runner."
    required: false
    default: ${{ github.token }}
  filePath:  
    description: 'The path to the directory containing the SPDX files to upload. Defaults to Actions working directory.'
    required: false
    default: '.'
  filePattern:
    description: 'The file name pattern for SPDX files to upload'
    required: false
    default: '*.spdx.json'
  correlator:
    description: 'The correlator property itself is the primary field used to keep independent submissions distinct.'
    required: false
    default: ${{ github.job }} 
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'upload-cloud'
  color: 'blue'
